title: Joe's GitHub Pages site
description: Just a place for me to get started with a GitHub Pages site
theme: just-the-docs

url: https://just-the-docs.github.io

#aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template

mermaid:
    version: "10.8.0"
